# Generated by Django 3.0.3 on 2020-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_auto_20200428_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='voice',
            field=models.TextField(),
        ),
    ]
