# Generated by Django 3.0.3 on 2020-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_auto_20200428_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='ipAddress',
            field=models.CharField(max_length=128),
        ),
    ]
