# Generated by Django 3.0.3 on 2020-04-28 17:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0011_auto_20200428_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='ipAddress',
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitorAddress',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitorTime',
            field=models.CharField(default=datetime.datetime(2020, 4, 28, 23, 9, 48, 555244), max_length=254),
            preserve_default=False,
        ),
    ]
