# Generated by Django 3.0.3 on 2020-04-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0013_choice1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice1',
        ),
    ]
